// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5u_dhYqPqQH9coCnXqhDkYtekN4ygtiA',
    appId: '1:439852574713:web:c85067bd9d90b7f19f7f28',
    messagingSenderId: '439852574713',
    projectId: 'smart-rp-b666e',
    authDomain: 'smart-rp-b666e.firebaseapp.com',
    storageBucket: 'smart-rp-b666e.appspot.com',
    measurementId: 'G-ZPBCDEEFLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvh6GNA-AA-0_knptnf4RLf6n0bWvO6Q',
    appId: '1:439852574713:android:feb5d8a2c59f553a9f7f28',
    messagingSenderId: '439852574713',
    projectId: 'smart-rp-b666e',
    storageBucket: 'smart-rp-b666e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb3j5WcC6_EKyvZK7WBj51HR--NmmNrP0',
    appId: '1:439852574713:ios:aebf7ccf65d090519f7f28',
    messagingSenderId: '439852574713',
    projectId: 'smart-rp-b666e',
    storageBucket: 'smart-rp-b666e.appspot.com',
    iosBundleId: 'com.example.smartRp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb3j5WcC6_EKyvZK7WBj51HR--NmmNrP0',
    appId: '1:439852574713:ios:aebf7ccf65d090519f7f28',
    messagingSenderId: '439852574713',
    projectId: 'smart-rp-b666e',
    storageBucket: 'smart-rp-b666e.appspot.com',
    iosBundleId: 'com.example.smartRp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5u_dhYqPqQH9coCnXqhDkYtekN4ygtiA',
    appId: '1:439852574713:web:02017e107cbe0e089f7f28',
    messagingSenderId: '439852574713',
    projectId: 'smart-rp-b666e',
    authDomain: 'smart-rp-b666e.firebaseapp.com',
    storageBucket: 'smart-rp-b666e.appspot.com',
    measurementId: 'G-WP2QE9ZT5P',
  );
}
